extractor:
  state_store:
    raw:
      database: "State Store"
      table: "Ice Cream API Datapoints Extractor"

  data_set_ext_id: ds_ice_cream_api
  backfill: False
  days: 30
  sites:
    - Oslo
    - Houston
    - Rotterdam

api:
  url: https://ice-cream-factory.inso-internal.cognite.ai

cognite:
  host: ${CDF_URL}
  project: ${CDF_PROJECT}

  idp-authentication:
    tenant: ${IDP_TENANT_ID}

    client-id: ${IDP_CLIENT_ID}
    secret: ${IDP_CLIENT_SECRET}
    scopes:
      - ${IDP_SCOPES}

  extraction_pipeline:
    external-id: ep_icapi_datapoints

logger:
  console:
    level: INFO
  file:
    path: "debug.log"
    level: DEBUG
