environment:
  name: benpetree
  project: benpetree
  type: dev
  selected:
    - modules/data_foundation/ice-cream-api

variables:
  modules:
    data_foundation:
      ice_cream_api_source_dataSetExternalId: ds_ice_cream_api
      uc_oee_dataSetExternalId: ds_uc_oee
      ice-cream-api:
        icapi_asset_extractor_source_id: '1234'
        icapi_timeseries_extractor_source_id: '4567'

  CDF_PROJECT: ${CDF_PROJECT}
  IDP_CLIENT_ID: ${IDP_CLIENT_ID}
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
  IDP_TENANT_ID: ${IDP_TENANT_ID}
  CDF_URL: ${CDF_URL}
  IDP_SCOPES: ${IDP_SCOPES}
