environment:
  name: test
  project: cdf-bootcamp-70-test
  type: test
  selected:
  - modules/

variables:
  modules:
    bootcamp:
      CDF_PROJECT: ${CDF_PROJECT} # ex. cdf-bootcamp-01-test
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR TEST/PROD DATA DEVELOPER ENTRA GROUP
      data_developer_source_id: b488e198-1643-4b79-8587-33f93c7bc761
      # OBJECT ID FOR TEST/PROD DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: 028cea4a-9a84-46b4-b7a1-b6a7a1acca81
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: b5400436-33f8-4882-bdcb-670152f5322c
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readonly_source_id: b5400436-33f8-4882-bdcb-670152f5322c
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      icapi_extractors_source_id: 855fb525-97e9-48e4-ac25-09b1c1745124
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      ice_cream_api:
        icapi_ds_external_id: ds_icapi

      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
